version: '2.13'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: healthy96band
      POSTGRES_USER: healthybandroot
      POSTGRES_DB: healthyband
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db